Fix distro check
Function platform.linux_distribution() removed since Python 3.8.

error message:

    Traceback (most recent call last):
      File "setup.py", line 23, in <module>
        if ('Fedora' == platform.linux_distribution()[0] or
    AttributeError: module 'platform' has no attribute 'linux_distribution'